services:
  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/meta_model_artifacts:/app/meta_model_artifacts:ro
      - ./config/deepsafe_config.json:/app/config/deepsafe_config.json:ro
    environment:
      PORT: 8000
      META_MODEL_ARTIFACTS_DIR: /app/meta_model_artifacts
      DEEPSAFE_CONFIG_FILE_PATH: /app/config/deepsafe_config.json
      LOG_LEVEL: info
    depends_on:
      - npr_deepfakedetection
      - universalfakedetect
      - cross_efficient_vit
    # expose:
    #   - "8000"
    networks:
      - deepsafe-network

  npr_deepfakedetection:
    build:
      context: .
      dockerfile: models/image/npr_deepfakedetection/Dockerfile
    restart: unless-stopped
    environment:
      MODEL_PORT: 5001
      PRELOAD_MODEL: "false"
      MODEL_TIMEOUT: 600
      USE_GPU: "false"
    # expose:
    #   - "5001"
    networks:
      - deepsafe-network

  universalfakedetect:
    build:
      context: .
      dockerfile: models/image/universalfakedetect/Dockerfile
    restart: unless-stopped
    environment:
      MODEL_PORT: 5004
      PRELOAD_MODEL: "false"
      MODEL_TIMEOUT: 600
      USE_GPU: "false"
    # expose:
    #   - "5004"
    networks:
      - deepsafe-network

  cross_efficient_vit:
    build:
      context: .
      dockerfile: models/video/cross_efficient_vit/Dockerfile
    restart: unless-stopped
    environment:
      MODEL_PORT: 7001
      PRELOAD_MODEL: "false"
      MODEL_TIMEOUT: 900
      USE_GPU: "false"
    # expose:
    #   - "7001"
    networks:
      - deepsafe-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - api
    # ports:
    #   - "80"
    networks:
      - deepsafe-network
      - dokploy-network

networks:
  deepsafe-network:
    driver: bridge
  dokploy-network:
    external: true
